# Generated by Django 4.1.7 on 2023-03-04 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'verbose_name': 'employees', 'verbose_name_plural': 'Employee'},
        ),
    ]
